###
GET http://localhost:3000/users
Authorization: {{access_token}}
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Marly Marley",
    "email": "marlymarley7@gmail.com",
    "password": "123456",
    "admin": false,
    "chavePix": "aaaaaaaaaaaaaaaa"
}
###
GET http://localhost:3000/users/1
###
DELETE http://localhost:3000/users/1
###
PATCH http://localhost:3000/users/10
Content-Type: application/json

{
    "name": "Marly Marley",
    "email": "marlymarley7@gmail.com",
    "password": "123456",
    "confirmPassword": "123456",
    "chavePix": "aaaaaaasdaaaaaaaaa"
}
###
# @name signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "marlymarley7@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}
###
@access_token = Bearer {{signin.response.body.access_token}}
###